### ISSUE TITLE
[bug] hacking data found

### ISSUE THREAD

**Issue by GoatGirl98** [nishanth17/factorize-integer#3]
A bug occured when the input number is `2152302898747`.
The program output `2152302898747^1`, while the real answer for this case is `6763^1 * 10627^1 * 29947^1`.
It seems to be related to the function `is_prime` , Miller-Rabin primality-test Algorithm.

**Comment by Schmitz-David** [comment]
This is a minor issue: in line 176 of utils.py, just replace 2152302898749 by 2152302898747. I think all other constants are correct.

**Comment by nishanth17** [comment]
@Schmitz-David Thank you for figuring this out - I updated the file!
